### ISSUE TITLE
when will you provide the pretrained model?

### ISSUE THREAD

**Issue by oneTaken** [svdbase/SVD-baselines#1]
It's useful to run the pretrained model to dive into this paper.

So would you provide the pretrained model?

**Comment by svdbase** [comment]
@oneTaken For which method?

**Comment by Tachyu** [comment]
Your paper mentioned the DML method. Is there a trained DML model for SVD?

**Comment by svdbase** [comment]
@Tachyu @oneTaken Please note that I use the code of DML provided by their authors. If you want to implement DML, please refer: https://github.com/MKLab-ITI/ndvr-dml. Furthermore, I didn't include the code of DML in this repo.
