### ISSUE TITLE
XOR operation in the Hamming Space

### ISSUE THREAD

**Issue by zhhezhhe** [svdbase/SVD-baselines#2]
```
def __hamming_dist__(b1, b2):
    if b1.ndim == 1:
        b1 = b1.reshape(1, -1)
    if b2.ndim == 1:
        b2 = b2.reshape(1, -1)

    bit = b1.shape[1]
    hamm = (bit - b1.dot(b2.T)) / 2  
    return int(hamm.squeeze().real)
```
This is not XOR operation. 
我测试了下，它貌似和直接计算4096D特征的欧式距离时间差不多的。请问论文中时间性能是怎么得到的呢？XOR操作有代码吗？

**Comment by jiangqy** [comment]
时间性能需要压缩编码、建表、粗排、重排。我们使用的是C++库做的。代码正在整理。可以参考repo：https://github.com/ZJULearning/hashingSearch

谢谢。

**Comment by zhhezhhe** [comment]
> 时间性能需要压缩编码、建表、粗排、重排。我们使用的是C++库做的。代码正在整理。可以参考repo：https://github.com/ZJULearning/hashingSearch
> 
> 谢谢。

感谢回复，我在follow这个工作，谢谢！
