### ISSUE TITLE
Can you share the other code of methods in the paper?

### ISSUE THREAD

**Issue by zhhezhhe** [svdbase/SVD-baselines#3]
Hi, I find some methods are not in these baselines, like `DML, CNNL, HDML`. Can you share them later? I wish I could follow your work. I didn't find these codes in other places. Thanks!

**Comment by jiangqy** [comment]
Thanks for your interest.

DML:  https://github.com/MKLab-ITI/ndvr-dml

CNNL can be implemented similarly to CNNV. 

HDML: https://norouzi.github.io/

The HDML version is matlab.

**Comment by zhhezhhe** [comment]
> Thanks for your interest.
> 
> DML: https://github.com/MKLab-ITI/ndvr-dml
> 
> CNNL can be implemented similarly to CNNV.
> 
> HDML: https://norouzi.github.io/
> 
> The HDML version is matlab.

Thanks a lot!
